<center> <h1> LAB -1 (Numpy) </h1> </center>


---
## TASK : 1

In [1]:
import numpy as np
arr = [i for i in range(1,21)]
arr = np.array(arr)
arr = arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [2]:
arr[:,4] = 0
arr

array([[ 1,  2,  3,  4,  0],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14,  0],
       [16, 17, 18, 19,  0]])

In [3]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  0,  6,  7,  8,  9,  0, 11, 12, 13, 14,  0, 16, 17,
       18, 19,  0])

---

## TASK : 2

In [4]:
arr2 = np.random.randint(10,50,25)
arr2 = arr2.reshape(5,5)
print(arr2)
print('-' * 20)
for i in range(5):
    print(f'Row {i+1} Sum:' , np.sum(arr2[i,:]))
    print(f'Row {i+1} Mean:' , np.mean(arr2[i,:]))
    print(f'Row {i+1} Min:' , np.min(arr2[i,:]))
    print(f'Row {i+1} Max:' , np.max(arr2[i,:]))
    print(f'Column {i+1} Sum:' , np.sum(arr2[:,i]))
    print(f'Column {i+1} Mean:' , np.mean(arr2[:,i]))
    print(f'Column {i+1} Min:' , np.min(arr2[:,i]))
    print(f'Column {i+1} Max:' , np.max(arr2[:,i]))
    


[[40 24 35 25 12]
 [10 41 15 25 16]
 [29 16 25 17 26]
 [33 36 19 35 48]
 [36 41 37 46 37]]
--------------------
Row 1 Sum: 136
Row 1 Mean: 27.2
Row 1 Min: 12
Row 1 Max: 40
Column 1 Sum: 148
Column 1 Mean: 29.6
Column 1 Min: 10
Column 1 Max: 40
Row 2 Sum: 107
Row 2 Mean: 21.4
Row 2 Min: 10
Row 2 Max: 41
Column 2 Sum: 158
Column 2 Mean: 31.6
Column 2 Min: 16
Column 2 Max: 41
Row 3 Sum: 113
Row 3 Mean: 22.6
Row 3 Min: 16
Row 3 Max: 29
Column 3 Sum: 131
Column 3 Mean: 26.2
Column 3 Min: 15
Column 3 Max: 37
Row 4 Sum: 171
Row 4 Mean: 34.2
Row 4 Min: 19
Row 4 Max: 48
Column 4 Sum: 148
Column 4 Mean: 29.6
Column 4 Min: 17
Column 4 Max: 46
Row 5 Sum: 197
Row 5 Mean: 39.4
Row 5 Min: 36
Row 5 Max: 46
Column 5 Sum: 139
Column 5 Mean: 27.8
Column 5 Min: 12
Column 5 Max: 48


---
## TASK : 3

In [5]:
arr3 = np.identity(4,dtype=int) * 5
arr3

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [6]:
arr3[3] = np.ones(4,dtype=int)
arr3

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [1, 1, 1, 1]])

---
## TASK : 4

In [9]:
arr4 = np.random.randint(0, 21, 15)
unique = len(set(arr4))
greater_than_10 = [index for index, value in enumerate(arr4) if value > 10]
print("Array:", arr4)
print("Unique Element Count:", unique)
print("Indices of elements greater than 10", greater_than_10)

Array: [ 4  3 15  1  6  8 13  1 19  2  8 20 20  2 16]
Unique Element Count: 11
Indices of elements greater than 10 [2, 6, 8, 11, 12, 14]


---
## TASK : 5

In [8]:
arr5 = np.random.rand(12)
arr5 = arr5.reshape(3,4)
arr5 = arr5.round(2)
arr5[:,1] = 0.5
arr5

array([[0.1 , 0.5 , 1.  , 0.89],
       [0.28, 0.5 , 0.3 , 0.54],
       [0.61, 0.5 , 0.73, 0.21]])