In [1]:
import numpy as np
import pandas as pd


---
### TASK-1

In [13]:
players = np.array([
    [180, 75, 150],   
    [175, 70, 120],   
    [190, 65, 200],   
    [200, 72, 180],
    [180, 80, 180]
])

players

array([[180,  75, 150],
       [175,  70, 120],
       [190,  65, 200],
       [200,  72, 180],
       [180,  80, 180]])

In [14]:
max_points_index = np.argmax(players[:, 2])  
players[max_points_index, 1] = 80  
players

array([[180,  75, 150],
       [175,  70, 120],
       [190,  80, 200],
       [200,  72, 180],
       [180,  80, 180]])

In [15]:
new_player = np.array([[185, 78, 130]]) 
players = np.vstack([players, new_player])
players


array([[180,  75, 150],
       [175,  70, 120],
       [190,  80, 200],
       [200,  72, 180],
       [180,  80, 180],
       [185,  78, 130]])

In [16]:
new= np.array([180, 54, 100])
print(players.shape)
print(new.shape)
# players = np.insert(players, 3, new, axis=1)

new_statistic = np.array([178, 65, 18])
index = 2
players = np.insert(players, index, new_statistic, axis=0)

(6, 3)
(3,)


In [17]:
min_p_idx = np.argmin(players[:, 2]) 
players = np.delete(players, min_p_idx, axis=0)
players

array([[180,  75, 150],
       [175,  70, 120],
       [190,  80, 200],
       [200,  72, 180],
       [180,  80, 180],
       [185,  78, 130]])

---
### TASK-2

In [18]:
purchase_amounts = np.array([100, 200, 50, 75, 150])
item_counts = np.array([2, 4, 1, 3, 2])

In [19]:
shallow_copy_amounts = purchase_amounts.copy()  
deep_copy_counts = item_counts.view() 
shallow_copy_amounts, deep_copy_counts

(array([100, 200,  50,  75, 150]), array([2, 4, 1, 3, 2]))

In [20]:
concatenated_array = np.concatenate((purchase_amounts, item_counts))
concatenated_array

array([100, 200,  50,  75, 150,   2,   4,   1,   3,   2])

In [21]:
split_array = np.split(concatenated_array, [len(purchase_amounts)])
split_array

[array([100, 200,  50,  75, 150]), array([2, 4, 1, 3, 2])]

In [22]:
split_array

[array([100, 200,  50,  75, 150]), array([2, 4, 1, 3, 2])]

In [23]:
purchase_amounts[0] = 500
item_counts[1] = 10

print("\nModified Original Purchase Amounts:")
print(purchase_amounts)
print("Modified Original Item Counts:")
print(item_counts)

print("\nShallow Copy of Purchase Amounts after Modification:")
print(shallow_copy_amounts)
print("Deep Copy of Item Counts after Modification:")
print(deep_copy_counts)


Modified Original Purchase Amounts:
[500 200  50  75 150]
Modified Original Item Counts:
[ 2 10  1  3  2]

Shallow Copy of Purchase Amounts after Modification:
[100 200  50  75 150]
Deep Copy of Item Counts after Modification:
[2 4 1 3 2]


---