In [1]:
import numpy as np 

In [2]:
np.__version__

'1.26.4'

In [3]:
np.__path__

['/opt/conda/lib/python3.10/site-packages/numpy']

In [4]:
import numpy as np
arr = np.array([4])
print(arr)
print(type(arr))

[4]
<class 'numpy.ndarray'>


In [5]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  [4]
arr.ndim:  1
arr.shape:  (1,)
arr.size:  1
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  8
arr.data:  <memory at 0x797a1b3e9900>
arr.strides:  (8,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [6]:
arr = np.array([[5,3,2,4],[8,9,6,-1],[9,2,-3,6]])
arr

array([[ 5,  3,  2,  4],
       [ 8,  9,  6, -1],
       [ 9,  2, -3,  6]])

In [7]:
for i in range(3):
    for j in range(3):
        print(arr[i,j])

5
3
2
8
9
6
9
2
-3


In [8]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)


array:  [[ 5  3  2  4]
 [ 8  9  6 -1]
 [ 9  2 -3  6]]
arr.ndim:  2
arr.shape:  (3, 4)
arr.size:  12
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  96
arr.data:  <memory at 0x797a1b516740>
arr.strides:  (32, 8)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [9]:
# Create a 1-D numpy array using array() constructor of numpy

mylist = [1, 4, 2, 5, 3]
arr = np.array(mylist, dtype=np.uint8)
arr = np.array([1, 4, 2, 5, 3], dtype=np.uint32)

print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions
print("arr.shape: ", arr.shape) # This is 1-D array having 5 columns, so return a tuple with one element
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (2*5=10)

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  [1 4 2 5 3]
arr.ndim:  1
arr.shape:  (5,)
arr.size:  5
arr.dtype:  uint32
arr.itemsize:  4
arr.nbytes:  20
arr.data:  <memory at 0x797a1b3e9780>
arr.strides:  (4,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [10]:
# creating 2-D (5x4) array using array constructor in numpy

mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("array: \n", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)


print("arr.data: ", arr.data)
print("arr.dtypes: ", arr.dtype)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]
arr.ndim:  2
arr.shape:  (5, 4)
arr.size:  20
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  160
arr.data:  <memory at 0x797a1b516740>
arr.dtypes:  int64
arr.strides:  (32, 8)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [11]:
arr[1,3]

8

In [12]:
# Another example
mylist = [[1], [4], [2], [5], [3]]
arr = np.array(mylist)
arr = np.array([[1], [2], [3]])
print("array: \n", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[1]
 [2]
 [3]]
arr.ndim:  2
arr.shape:  (3, 1)
arr.size:  3
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  24
arr.data:  <memory at 0x797a1b516740>
arr.strides:  (8, 8)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [13]:
# creating 3-D (5x4x3) array using array constructor in numpy
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4], [7, 3, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4], [2, 6, 2]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0], [5, 6, 9]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7], [2, 0, 4]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2], [1, 3, 8]],
         ]
arr = np.array(mylist, dtype=np.uint8)


print("array: \n", arr)
print("arr.ndim: ", arr.ndim)    # get number of dimensions (3-D array)
print("arr.shape: ", arr.shape)  # get dimension size.For a 3-D array, return a tuple with three elements
print("arr.size: ", arr.size)    # get total number of elements (5*4*3=60 elements)
print("arr.dtype: ", arr.dtype)  # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*60=4800)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[[1 2 3]
  [5 6 7]
  [3 2 4]
  [7 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]
  [2 6 2]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]
  [5 6 9]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]
  [2 0 4]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]
  [1 3 8]]]
arr.ndim:  3
arr.shape:  (5, 4, 3)
arr.size:  60
arr.dtype:  uint8
arr.itemsize:  1
arr.nbytes:  60
arr.data:  <memory at 0x797a1b4cbd30>
arr.strides:  (12, 3, 1)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [14]:
# Strides of 1-D array
import numpy as np
mylist = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[3]) # jump 3*8=24 bytes and then read 8 bytes

array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.data:  <memory at 0x797a1b3e9b40>
arr.shape:  (12,)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (8,)
3


In [15]:
# Strides of 2-D array
import numpy as np
mylist = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,2]) # jump 1*32+2*8=48 bytes and then read 8 bytes

array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr.data:  <memory at 0x797a1b516740>
arr.shape:  (3, 4)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 8)
6


In [16]:
# Creating 1-Dimensional array of all zeros
arr = np.zeros(3,dtype=np.uint64)
arr
# Notice that the elements are having the default data type as the float. That’s why the zeros are 0.

array([0, 0, 0], dtype=uint64)

In [17]:
# Creating 2-Dimensional array having 3 columns filled with ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Creating 2-Dimensional array having 3 columns filled with junk values
arr = np.empty((2,3,3), dtype=np.int16)
arr

array([[[ -6128, -22975,  22191],
        [     0,      0,      0],
        [     0,      0, -28624]],

       [[-22986,  22191,      0],
        [ 15328, -22999,  22191],
        [     0,     48,      0]]], dtype=int16)

In [19]:
arr = np.full((2,3), 21.5)
arr

array([[21.5, 21.5, 21.5],
       [21.5, 21.5, 21.5]])

In [20]:
arr = np.full(7, 54)
arr

array([54, 54, 54, 54, 54, 54, 54])

In [21]:
arr = np.full(7, 21.5)
arr

array([21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5])

In [22]:
arr = np.full((2,3), 21.5)
arr

array([[21.5, 21.5, 21.5],
       [21.5, 21.5, 21.5]])

In [23]:
arr = np.full((5,2,3), 21.5)
arr

array([[[21.5, 21.5, 21.5],
        [21.5, 21.5, 21.5]],

       [[21.5, 21.5, 21.5],
        [21.5, 21.5, 21.5]],

       [[21.5, 21.5, 21.5],
        [21.5, 21.5, 21.5]],

       [[21.5, 21.5, 21.5],
        [21.5, 21.5, 21.5]],

       [[21.5, 21.5, 21.5],
        [21.5, 21.5, 21.5]]])

In [24]:
# creating 2-D array using eye function
eye_arr = np.eye(3,3,1)
eye_arr

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:

eye_arr = np.eye(4,4,-1)
eye_arr

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
eye_arr = np.eye(4, 3, k = 1, dtype=int)
eye_arr

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
# convert the space separated string '25 30 35 40' into an floats array
arr = np.fromstring('25 30 35 40', sep=' ')
arr

array([25., 30., 35., 40.])

In [28]:
#will return error; as homogeneousity fails
arr = np.fromstring('25 30 34.4 40', sep='-',dtype=int)
arr

/tmp/ipykernel_17/926681347.py:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  arr = np.fromstring('25 30 34.4 40', sep='-',dtype=int)


array([25])

In [29]:
# convert the space separated string '25 30 35 40' into an floats array
arr = np.fromstring('25-3-35-40', sep='-',dtype=np.int8)
arr

array([25,  3, 35, 40], dtype=int8)

In [30]:
arr = np.arange(10)
print(arr)
print(type(arr))
print(arr.dtype),

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


(None,)

In [31]:
arr = np.arange(3,15,2)
arr

array([ 3,  5,  7,  9, 11, 13])

In [32]:
arr = np.arange(-1, -4, -.5)
arr

array([-1. , -1.5, -2. , -2.5, -3. , -3.5])

In [33]:
arr = np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [34]:
arr = np.linspace(-1, -4)
arr

array([-1.        , -1.06122449, -1.12244898, -1.18367347, -1.24489796,
       -1.30612245, -1.36734694, -1.42857143, -1.48979592, -1.55102041,
       -1.6122449 , -1.67346939, -1.73469388, -1.79591837, -1.85714286,
       -1.91836735, -1.97959184, -2.04081633, -2.10204082, -2.16326531,
       -2.2244898 , -2.28571429, -2.34693878, -2.40816327, -2.46938776,
       -2.53061224, -2.59183673, -2.65306122, -2.71428571, -2.7755102 ,
       -2.83673469, -2.89795918, -2.95918367, -3.02040816, -3.08163265,
       -3.14285714, -3.20408163, -3.26530612, -3.32653061, -3.3877551 ,
       -3.44897959, -3.51020408, -3.57142857, -3.63265306, -3.69387755,
       -3.75510204, -3.81632653, -3.87755102, -3.93877551, -4.        ])

In [35]:
arr = np.random.rand(5)*100
arr

array([85.78133155, 99.70617166, 41.53780763, 85.03061185, 54.92254956])

In [36]:
# creating 1-D array of size 6 of int type b/w interval (1,100) 
arr = np.random.randint(low=1, high=101, size=6)
arr

array([29, 76,  5, 44, 98,  5])

In [37]:
# By passing a tuple to size means rows and columns
arr = np.random.randint(low = 1, high = 10, size = (3,3))
arr

array([[3, 4, 2],
       [6, 3, 8],
       [8, 2, 4]])

In [38]:
# creating a 2-D array
mylist = [[0, 1],[2, 3]]
arr1 = np.array(mylist)
print("A 2-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)

A 2-D array 
 [[0 1]
 [2 3]]

 Converted Array 
 [[0 0]
 [0 0]]


In [39]:
# creating 1-D array
arr1 = np.arange(10)
print("A 1-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)

A 1-D array 
 [0 1 2 3 4 5 6 7 8 9]

 Converted Array 
 [0 0 0 0 0 0 0 0 0 0]
