In [1]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 100, size = 5)
arr2 = np.random.randint(low = 1, high = 100, size = 3)
print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr3 = np.concatenate((arr1, arr2))
arr3 = np.concatenate((arr1, arr2), axis=0)
print("\nnp.concatenate((arr1,arr2)) = ", arr3)

arr1 =  [12 76 46 76 93]
arr2 =  [35 37  9]

np.concatenate((arr1,arr2)) =  [12 76 46 76 93 35 37  9]


**Example:** Concatenate two 2-D Arrays along `axis=0` (vertically/row-wise). The number of columns of two arrays must match.

In [2]:
arr1 = np.random.randint(low = 1, high = 10, size = (2,3))
arr2 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

arr3 = np.concatenate((arr1, arr2), axis=0)
print("\nnp.concatenate((arr1,arr2)) = \n", arr3)

arr1 = 
 [[8 5 2]
 [4 3 4]]
arr2 = 
 [[8 9 9]
 [9 8 1]
 [3 6 3]]

np.concatenate((arr1,arr2)) = 
 [[8 5 2]
 [4 3 4]
 [8 9 9]
 [9 8 1]
 [3 6 3]]


**Example:** Concatenate two 2-D Arrays along `axis=1` (horizontally/column-wise). The number of rows of two arrays must match.

In [3]:
arr1 = np.random.randint(low = 1, high = 10, size = (2,2))
arr2 = np.random.randint(low = 1, high = 10, size = (2,3))
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

arr3 = np.concatenate((arr1, arr2), axis=1)
print("\nnp.concatenate((arr1,arr2)) = \n", arr3)

arr1 = 
 [[2 4]
 [2 6]]
arr2 = 
 [[9 4 4]
 [5 8 2]]

np.concatenate((arr1,arr2)) = 
 [[2 4 9 4 4]
 [2 6 5 8 2]]


## 2. Stacking NumPy Arrays
- Concatenating joins a sequence of arrays along an existing axis, and stacking joins a sequence of arrays along existing as well as along a new axis.
- We can perform stacking along three dimensions:
    - `np.vstack()` : it performs vertical stacking along the rows.
    - `np.hstack()` : it performs horizontal stacking along with the columns.
    - `np.dstack()` : it performs in-depth stacking along a new third axis (depth).

**Note:** 
- `numpy.stack()` is the most general of the three methods, offering an axis parameter for specifying which way to put the arrays together.
- `np.column_stack()` is used to stack 1-D arrays as columns into 2-D array.
- `np.row_stack()` is used to stack 1-D arrays as rows into 2-D array.

**Example: `np.row_stack()`**

In [4]:
#ROW STACK
import numpy as np
arr1 = np.array([2,5,1])
arr2 = np.array([3,6,2])

print("arr1 = ", arr1)
print("arr2 = ", arr2)
  
arr3 = np.row_stack((arr1, arr2))

print ("\nnp.row_stack((arr1, arr2)):\n ", arr3)

arr1 =  [2 5 1]
arr2 =  [3 6 2]

np.row_stack((arr1, arr2)):
  [[2 5 1]
 [3 6 2]]


C:\Users\PMLS\AppData\Local\Temp\ipykernel_31048\1151901144.py:9: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr3 = np.row_stack((arr1, arr2))


**Example: `np.column_stack()`**

In [5]:
#COLUMN STACK
import numpy as np
arr1 = np.array([2,5,1])
arr2 = np.array([3,6,2])

print("arr1 = ", arr1)
print("arr2 = ", arr2)
  
arr3 = np.column_stack((arr1, arr2))

print ("\nnp.column_stack((arr1, arr2)):\n ", arr3)

arr1 =  [2 5 1]
arr2 =  [3 6 2]

np.column_stack((arr1, arr2)):
  [[2 3]
 [5 6]
 [1 2]]


**Example:** Perform vertical stacking of two 1-D Arrays, which must have the same size/length.

In [10]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 10, size = 4)
arr2 = np.random.randint(low = 1, high = 10, size = 4)

print("arr1 = ", arr1)
print("arr2 = ", arr2)
  
arr3 = np.vstack((arr1, arr2))

print ("\nnp.vstack((arr1, arr2)):\n ", arr3)

arr1 =  [1 6 7 3]
arr2 =  [3 7 2 7]

np.vstack((arr1, arr2)):
  [[1 6 7 3]
 [3 7 2 7]]


Note: The output array is a 2-D array

**Example:** Perform vertical stacking of two 2-D Arrays. The number of columns of two arrays must match

In [11]:
arr1 = np.random.randint(low = 1, high = 10, size = (2,3))
arr2 = np.random.randint(low = 1, high = 10, size = (3,3))

print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

arr3 = np.vstack((arr1, arr2))
print ("\n np.vstack((arr1, arr2)):\n ", arr3)

arr1 = 
 [[8 4 8]
 [1 2 1]]
arr2 = 
 [[4 4 6]
 [6 5 8]
 [5 2 6]]

 np.vstack((arr1, arr2)):
  [[8 4 8]
 [1 2 1]
 [4 4 6]
 [6 5 8]
 [5 2 6]]


**Example:** Perform horizontal stacking of two 1-D Arrays, which can be of different  size/length

In [12]:
arr1 = np.random.randint(low = 1, high = 10, size = 5)
arr2 = np.random.randint(low = 1, high = 10, size = 4)
print("arr1 = ", arr1)
print("arr2 = ", arr2)
  
arr3 = np.hstack((arr1, arr2))
print ("\n np.hstack((arr1, arr2)):\n ", arr3)

arr1 =  [4 3 7 1 1]
arr2 =  [5 6 4 7]

 np.hstack((arr1, arr2)):
  [4 3 7 1 1 5 6 4 7]


Note: The output array is a 1-D array

**Example:** Perform horizontal stacking of two 2-D Arrays. The number of rows of two arrays must match

In [13]:
arr1 = np.random.randint(low = 1, high = 10, size = (2,2))
arr2 = np.random.randint(low = 1, high = 10, size = (2,3))
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

arr3 = np.hstack((arr1, arr2))
print ("\n np.hstack((arr1, arr2)):\n ", arr3)

arr1 = 
 [[2 8]
 [6 4]]
arr2 = 
 [[8 9 6]
 [5 2 7]]

 np.hstack((arr1, arr2)):
  [[2 8 8 9 6]
 [6 4 5 2 7]]


### e. Using `np.stack()`

- The `np.stack()` method is used to join a sequence of same dimension arrays along a new axis.
- The axis parameter specifies the index of the new axis in the dimensions of the result. 
- For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.
```
np.stack(a1, a2, a3, ..., axis=0)
```

- Where `tup` is comma separated ndarrays
- 1-D or 2-D arrays must have the same shape, while n-D arrays must have the same shape along all but the third axis.
- It returns the array formed by stacking the given arrays, which has one more dimension than the input arrays.
- This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis).



**Note:** Concatenating joins a sequence of tensors along an existing axis, and stacking joins a sequence of tensors along a new axis

**Example:** Perform stacking of two 1-D Arrays, which must have the same size/shape.

In [14]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 10, size = 4)
arr2 = np.random.randint(low = 1, high = 10, size = 4)
print("arr1 = ", arr1)
print("arr2 = ", arr2)
  
# Stacking two 1-D arrays along axis 0 using stack()
arr3 = np.stack((arr1, arr2), axis = 0)
print ("\n np.stack(arr1, arr2, axis=0):\n ", arr3)
# Stacking the two 1-D arrays using row_stack()
arr4 = np.row_stack((arr1, arr2))
print ("\n np.row_stack(arr1, arr2)):\n ", arr4)
  

# Stacking two 1-D arrays along axis 1 using stack()
arr5 = np.stack((arr1, arr2), axis = 1)
print ("\n np.stack((arr1, arr2), axis=1):\n ", arr5)
# Stacking the two 1-D arrays using column_stack()
arr6 = np.column_stack((arr1, arr2))
print ("\n np.column_stack(arr1, arr2):\n ", arr6)

arr1 =  [8 8 7 3]
arr2 =  [3 8 6 2]

 np.stack(arr1, arr2, axis=0):
  [[8 8 7 3]
 [3 8 6 2]]

 np.row_stack(arr1, arr2)):
  [[8 8 7 3]
 [3 8 6 2]]

 np.stack((arr1, arr2), axis=1):
  [[8 3]
 [8 8]
 [7 6]
 [3 2]]

 np.column_stack(arr1, arr2):
  [[8 3]
 [8 8]
 [7 6]
 [3 2]]


C:\Users\PMLS\AppData\Local\Temp\ipykernel_31048\2707974652.py:11: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr4 = np.row_stack((arr1, arr2))


**Example:** Perform stacking of two 2-D Arrays, which must have the same size/shape.

In [15]:
import numpy as np
arr1 = np.array([[4,3,1],[5,6,2]])
arr2 = np.array([[5,1,8],[3,9,1]])

print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

# Stacking the two arrays along axis 0
arr3 = np.stack((arr1, arr2), axis = 0)
print ("\n np.stack((arr1, arr2), axis=0): \n", arr3)

print("shape of arr3:", arr3.shape)

arr1 = 
 [[4 3 1]
 [5 6 2]]
arr2 = 
 [[5 1 8]
 [3 9 1]]

 np.stack((arr1, arr2), axis=0): 
 [[[4 3 1]
  [5 6 2]]

 [[5 1 8]
  [3 9 1]]]
shape of arr3: (2, 2, 3)


In [16]:
import numpy as np
arr1 = np.array([[4,3,1],[5,6,2]])
arr2 = np.array([[5,1,8],[3,9,1]])

print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

# Stacking the two arrays along axis 1
arr3 = np.stack((arr1, arr2), axis = 1)
print ("\n np.stack((arr1, arr2), axis=1): \n", arr3)

print("shape of arr3:", arr3.shape)

arr1 = 
 [[4 3 1]
 [5 6 2]]
arr2 = 
 [[5 1 8]
 [3 9 1]]

 np.stack((arr1, arr2), axis=1): 
 [[[4 3 1]
  [5 1 8]]

 [[5 6 2]
  [3 9 1]]]
shape of arr3: (2, 2, 3)


In [17]:
import numpy as np
arr1 = np.array([[4,3,1],[5,6,2]])
arr2 = np.array([[5,1,8],[3,9,1]])

print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

  
# Stacking the two arrays along last axis
arr3 = np.stack((arr1, arr2), axis = -1)
print ("\n np.stack((arr1, arr2), axis=-1):\n ", arr3)
print("shape of arr3:", arr3.shape)

arr1 = 
 [[4 3 1]
 [5 6 2]]
arr2 = 
 [[5 1 8]
 [3 9 1]]

 np.stack((arr1, arr2), axis=-1):
  [[[4 5]
  [3 1]
  [1 8]]

 [[5 3]
  [6 9]
  [2 1]]]
shape of arr3: (2, 3, 2)


## 3. Splitting NumPy Arrays
- Splitting is reverse operation of Joining, and is used to split one array into multiple arrays....
- We can perform splitting along three dimensions:
    - `np.split()` : Split array into a list of multiple sub-arrays of equal size.
    - `np.hsplit()` : Split array into multiple sub-arrays horizontally (column wise).
    - `np.vsplit()` : Split array into multiple sub-arrays vertically (row wise).

In [18]:
arr1 = np.random.randint(low = 1, high = 10, size = 20)
print("arr1:\n",arr1)

# The split size must be a factor of array size (can be 1, 2, 4, 5, 10) 
print("\nSub-arrays: \n", np.split(arr1, 4))

arr1:
 [5 8 8 6 6 4 4 7 5 3 5 1 2 1 8 9 4 9 5 3]

Sub-arrays: 
 [array([5, 8, 8, 6, 6], dtype=int32), array([4, 4, 7, 5, 3], dtype=int32), array([5, 1, 2, 1, 8], dtype=int32), array([9, 4, 9, 5, 3], dtype=int32)]


In [19]:
# create an array of float type
arr1 = np.random.randint(low = 1, high = 10, size = 13)
print("arr1:\n",arr1)

# The array_split() will not flag an error if size is not a factor of array size (will manage)
print("\nSub-arrays: \n", np.array_split(arr1, 4))

arr1:
 [3 2 5 9 2 2 1 2 9 2 5 2 5]

Sub-arrays: 
 [array([3, 2, 5, 9], dtype=int32), array([2, 2, 1], dtype=int32), array([2, 9, 2], dtype=int32), array([5, 2, 5], dtype=int32)]


In [20]:
# create an array of float type with 4 rows and 4 columns with sequential values from 0 to 15
arr1 = np.arange(16.0).reshape(4,4)
# print array
print("arr1:\n",arr1)
print("shape: ", arr1.shape)

arr1:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
shape:  (4, 4)


In [ ]:
# horizontally split array into 2 subarrays
print("\nSub-arrays: \n", np.hsplit(arr1, 2))

**Example:**

In [21]:
# create an array of float type with 4 rows and 5 columns with sequential values from 0 to 19
arr1 = np.arange(16.0).reshape(4,4)
print("arr1:\n",arr1)
print("shape: ", arr1.shape)

arr1:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
shape:  (4, 4)


In [23]:
# vertically split array into 2 subarrays (remember size argument must be a factor of number of rows )
print("\nSub-arrays: \n", np.hsplit(arr1, 2))


Sub-arrays: 
 [array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
