In [47]:
import numpy as np

In [48]:
np.__version__

'2.2.0'

In [49]:
np.__path__

['C:\\Users\\PMLS\\Desktop\\SEM-5\\Into to DS\\LAB\\.venv\\Lib\\site-packages\\numpy']

In [50]:
np.dtype

numpy.dtype

In [51]:
array  = np.array(1)

In [52]:
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print(array.strides)
print(array.itemsize)
print(array.nbytes)
print(array.data)
print(array.flags)

()
0
int64
1
()
8
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [53]:
array = np.array([1, 2, 3])

In [54]:
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print(array.strides)
print(array.itemsize)
print(array.nbytes)
print(array.data)
print(array.flags)

(3,)
1
int64
3
(8,)
8
24
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [55]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [56]:
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print(array.strides)
print(array.itemsize)
print(array.nbytes)
print(array.data)
print(array.flags)

(2, 3)
2
int64
6
(24, 8)
8
48
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [57]:
array =  np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [58]:
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print(array.strides)
print(array.itemsize)
print(array.nbytes)
print(array.data)
print(array.flags)

(2, 2, 3)
3
int64
12
(48, 24, 8)
8
96
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [59]:
# Strides of 1-D array
import numpy as np
mylist = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[3]) # jump 3*8=24 bytes and then read 8 bytes

array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.data:  <memory at 0x000001761C16BAC0>
arr.shape:  (12,)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (8,)
3


In [60]:
# Strides of 2-D array
import numpy as np
import numpy as np
mylist = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,2]) # jump 1*32+2*8=48 bytes and then read 8 byte

array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr.data:  <memory at 0x000001761C2C71D0>
arr.shape:  (3, 4)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 8)
6


In [61]:
# Strides of 3-D array
import numpy as np
mylist = [
          [[0, 1], [2, 3]],
          [[4, 5], [6, 7]],
          [[8, 9], [10, 11]]
         ]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,1,1]) # jump 1*32 + 0*16 + 1*8 =40 bytes and then read 8 bytes

array: 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
arr.data:  <memory at 0x000001761C083880>
arr.shape:  (3, 2, 2)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 16, 8)
7


In [62]:
# Creating 1-Dimensional array of all zeros
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [63]:
# Creating 2-Dimensional array of all zeros
arr = np.zeros((2, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
arr = np.zeros((2,3), dtype=np.int16)
arr, arr.nbytes

(array([[0, 0, 0],
        [0, 0, 0]], dtype=int16),
 12)

In [66]:
# Creating 3-Dimensional array of all zeros
arr = np.zeros((2, 3, 4))
for i in range(2):
    for j in range(3):
        for k in range(4):
            print(arr[i, j, k],end=' ')
        print('     ')
    print()

0.0 0.0 0.0 0.0      
0.0 0.0 0.0 0.0      
0.0 0.0 0.0 0.0      

0.0 0.0 0.0 0.0      
0.0 0.0 0.0 0.0      
0.0 0.0 0.0 0.0      



In [67]:
# Creating one-dimensional array with ones
arr = np.ones(3)
arr

array([1., 1., 1.])

In [68]:
# Creating two-dimensional array with ones
arr = np.ones((2, 3))

In [69]:
arr = np.ones((2, 3), dtype=np.int16)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [71]:
# Creating 3-Dimensional array of all ones
arr = np.ones((2, 3, 4))
arr 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [74]:
# Creating one-dimensional array with a specific value
arr = np.full((4,6), 5)
arr

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [75]:
np.full((4,6), 5, dtype=np.int16)


array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]], dtype=int16)

In [76]:
# Creating 2-Dimensional array with a specific value
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [79]:
np.ones((2, 3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.]])

In [81]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.eye(5,5,dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [86]:
np.eye(5,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [87]:
np.eye(5,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [91]:
np.random.rand(2,3)

array([[0.59982264, 0.17888863, 0.21515008],
       [0.21901818, 0.54717456, 0.46064143]])

In [96]:
np.random.rand(2,3,4) * 10

array([[[8.71481185, 1.67018679, 5.47465968, 9.08742201],
        [5.39721322, 3.6538884 , 2.08784691, 3.68769961],
        [8.01655617, 3.99212417, 0.546892  , 1.72731418]],

       [[8.38075436, 6.26492545, 4.46757021, 7.77506761],
        [6.26129871, 0.98903824, 8.2613854 , 7.03840418],
        [4.78286731, 9.94745314, 1.1643944 , 5.05124313]]])

In [98]:
np.random.randint(5)


4

In [100]:
np.random.randint(low=3, high=10, size=(7,3))

array([[6, 6, 8],
       [6, 3, 7],
       [7, 5, 5],
       [4, 3, 7],
       [8, 6, 3],
       [6, 7, 6],
       [5, 5, 4]], dtype=int32)

In [103]:
# NumPy array # NumPy array upcast data type of all elements to bigger datatype in case of different types
import numpy as np
array1 = np.array([3.5, True, 9, 2.7, False])
print(array1)
print(type(array1))
print(type(array1[1]))


[3.5 1.  9.  2.7 0. ]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [106]:
# NumPy array upcast data type of all elements to bigger datatype in case of different types
import numpy as np
array1 = np.array([3.5, True, 9, 2.7, False], dtype=int)
print(array1)
print(type(array1))
print(type(array1[1]))

[3 1 9 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [109]:
from array import array
array('i', [1, 2, 3, 4, 5])

array('i', [1, 2, 3, 4, 5])

In [112]:
array("f", [3, 6, 9, 2])  

array('f', [3.0, 6.0, 9.0, 2.0])

In [114]:
array("d", [3, 6, 9, 2])

array('d', [3.0, 6.0, 9.0, 2.0])

In [118]:
np.array([3, 6, 9, 2], dtype=np.float32) + 7

array([10., 13., 16.,  9.], dtype=float32)