In [2]:
import numpy as np
arr = np.random.randint(low = 1, high = 100, size = 10)
print("Original Array \n", arr)
arr[2] = 333
arr[-1] = 777
print("Updated Array \n", arr)

Original Array 
 [21 64 42 91 22 79 40 84 91 92]
Updated Array 
 [ 21  64 333  91  22  79  40  84  91 777]


In [3]:
arr = np.random.randint(low = 1, high = 10, size = (4, 4))
print("Original Array \n", arr)
arr[0][1] = 77
arr[1][2] = 66
arr[2][-1] = 22
print("Updated Array \n", arr)

Original Array 
 [[7 4 7 1]
 [3 9 2 3]
 [7 4 8 5]
 [4 5 5 9]]
Updated Array 
 [[ 7 77  7  1]
 [ 3  9 66  3]
 [ 7  4  8 22]
 [ 4  5  5  9]]


## 2. Append New Elements to Numpy Arrays
- The `np.append()` method allows us to insert new values at the end of a NumPy array.
- The method always returns a copy of the existing numpy array with the values appended to the given axis.
```
np.append(arr, values, axis=None)
```
- Where,
    - `arr` is the array in which we want to append
    - `values` must be of the correct shape (the same shape as `arr` excluding `axis`)
    - If `axis` is not specified, both `arr` and `values` are flattened before use.
    - If `axis` is specified, then `values` must be of the correct shape (the same shape as `arr` excluding `axis`)
- The original array remains as such, as it does not occur in-place.

In [3]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 100, size = 10)
print("arr1 = ", arr1)

arr1 =  [ 4 52 36 31 93 91 29 78  1 89]


In [4]:
# You can add a scalar value or a list of values at the end of a 1-D array
arr2 = np.append(arr1, [101, 202,303])
print("After append:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After append:
arr1 =  [ 4 52 36 31 93 91 29 78  1 89]
arr2 =  [  4  52  36  31  93  91  29  78   1  89 101 202 303]


In [5]:
print(id(arr1))
print(id(arr2))

1875357014736
1875357017520


### b. Appending Elements in 2-D Arrays

**Example:** In case of 2-D Arrays if `axis` is not mentioned both `arr` and `values` are flattened before use

In [6]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[8 7 1]
 [7 7 4]
 [4 6 7]]


In [7]:
# If the axis is not mentioned, values can be of any shape and both `arr` and `values` are flattened before use.
arr2 = np.append(arr1, [101, 202,303, 404, 505])
print("After append:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After append:
arr1 = 
 [[8 7 1]
 [7 7 4]
 [4 6 7]]
arr2 =  [  8   7   1   7   7   4   4   6   7 101 202 303 404 505]


In [8]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,3))
print("arr1 = \n", arr1)
print("shape: ", arr1.shape)

arr1 = 
 [[2 7 6]
 [2 5 1]
 [9 6 2]
 [3 9 7]]
shape:  (4, 3)


In [9]:
# For appending at axis 0, the values argument must the same shape as `arr` excluding `axis`
# so the values should be a row vector, and in this case of shape (1,3), having 1 row and 3 columns
arr2 = np.append(arr1, [[101, 202,303]], axis=0)
print("After append:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After append:
arr1 = 
 [[2 7 6]
 [2 5 1]
 [9 6 2]
 [3 9 7]]
arr2 = 
 [[  2   7   6]
 [  2   5   1]
 [  9   6   2]
 [  3   9   7]
 [101 202 303]]


In [10]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,3))
print("arr1 = \n", arr1)
print("shape: ", arr1.shape)

arr1 = 
 [[3 5 4]
 [7 3 6]
 [5 5 3]
 [9 4 9]]
shape:  (4, 3)


In [11]:
# For appending at axis 1, the values argument must the same shape as `arr` excluding `axis`
# so the values should be a column vector of shape (4,1), having 4 rows and 1 column
arr2 = np.append(arr1, [[101], [202], [303], [404]], axis=1)
print("After append:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After append:
arr1 = 
 [[3 5 4]
 [7 3 6]
 [5 5 3]
 [9 4 9]]
arr2 = 
 [[  3   5   4 101]
 [  7   3   6 202]
 [  5   5   3 303]
 [  9   4   9 404]]


## 3. Inserting New Elements in Numpy Arrays
- The `np.insert()` method allows us to insert new values along the given axis before the given index.
- The method always returns a copy of the existing numpy array with the values inserted to the given axis.
```
np.insert(arr, index, values, axis=None)
```
- Where,
    - `arr` is the array in which we want to insert
    - `index` is the index before which we want to insert
    - `values` [array_like] values to be added in the `arr`
    - If `axis` is not specified, both `arr` and `values` are flattened before use.
    - If `axis` is zero, a row is inserted (For 2-D arrays)
    - If `axis` is one, a column is inserted (For 2-D arrays)
- The original array remains as such, as it does not occur in-place.

### a. Inserting Elements in 1-D Arrays

In [12]:
arr1 = np.random.randint(low = 1, high = 100, size = 5)
print("arr1 = ", arr1)

arr1 =  [47 86 59 86 89]


In [13]:
# You can insert a scalar value or a list of values in between array elements before the mentioned index
arr2 = np.insert(arr1, 3, [55, 66,77])
print("After insert:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After insert:
arr1 =  [47 86 59 86 89]
arr2 =  [47 86 59 55 66 77 86 89]


### b. Inserting Elements in 2-D Arrays

**Example:** In case of 2-D array, if `axis` is not mentioned the array is flattened first

In [14]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[4 4 1 4]
 [2 8 9 1]
 [7 2 9 6]]


In [15]:
# Inserting a single value
arr2 = np.insert(arr1, 4, 55)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After insert:
arr1 = 
 [[4 4 1 4]
 [2 8 9 1]
 [7 2 9 6]]
arr2 =  [ 4  4  1  4 55  2  8  9  1  7  2  9  6]


In [17]:
# Inserting a multiple values
arr2 = np.insert(arr1, 4, [55, 66])
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After insert:
arr1 = 
 [[4 4 1 4]
 [2 8 9 1]
 [7 2 9 6]]
arr2 =  [ 4  4  1  4 55 66  2  8  9  1  7  2  9  6]


**Example:** If axis=0, value(s) are added as a row before mentioned index

In [18]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[8 7 1 7]
 [8 4 6 5]
 [6 1 9 3]]


In [19]:
# For axis = 0, note how the scalar value is replicated before insertion
arr2 = np.insert(arr1, 2, 55, axis=0)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[8 7 1 7]
 [8 4 6 5]
 [6 1 9 3]]
arr2 = 
 [[ 8  7  1  7]
 [ 8  4  6  5]
 [55 55 55 55]
 [ 6  1  9  3]]


In [20]:
# For axis=0, note the size of values has to be 4 in this case (equal to number of columns)
arr2 = np.insert(arr1, 2, [55, 66, 77, 88], axis=0)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[8 7 1 7]
 [8 4 6 5]
 [6 1 9 3]]
arr2 = 
 [[ 8  7  1  7]
 [ 8  4  6  5]
 [55 66 77 88]
 [ 6  1  9  3]]


**Example:** If axis=1, value(s) are added as a column at mentioned index

In [21]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[1 7 6 2]
 [8 3 1 9]
 [3 6 2 3]]


In [22]:
# For axis = 1, note how the scalar value is replicated before insertion
arr2 = np.insert(arr1, 2, 55, axis=1)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[1 7 6 2]
 [8 3 1 9]
 [3 6 2 3]]
arr2 = 
 [[ 1  7 55  6  2]
 [ 8  3 55  1  9]
 [ 3  6 55  2  3]]


In [23]:
# For axis=1, note the size of values has to be 3 in this case (equal to number of rows)
arr2 = np.insert(arr1, 2, [55, 66, 77], axis=1)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[1 7 6 2]
 [8 3 1 9]
 [3 6 2 3]]
arr2 = 
 [[ 1  7 55  6  2]
 [ 8  3 66  1  9]
 [ 3  6 77  2  3]]


## 4. Deleting  Elements of Numpy Arrays
- The `np.delete()` method allows us to delete value(s) from an array at the given index
- This function always returns a copy of the existing numpy array with the values deleted from the given axis.
- If axis is not specified, values can be of any shape and will be flattened before use
```
np.delete(arr, index, axis=None)
```
- The original array remains as such, as it does not occur in-place.

### a. Deleting Elements from a 1-D Arrays

In [24]:
arr1 = np.random.randint(low = 1, high = 10, size = 5)
print("arr1 = ", arr1)

arr1 =  [7 4 5 9 9]


In [25]:
# You can delete a scalar value from a specific index
arr2 = np.delete(arr1, 3)
print("After delete:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After delete:
arr1 =  [7 4 5 9 9]
arr2 =  [7 4 5 9]


In [26]:
arr1 = np.random.randint(low = 1, high = 100, size = 10)
print("arr1 = ", arr1)

arr1 =  [93  3 28  5 97  8 51 32 15 83]


In [27]:
# You can delete a list of values in between array elements from specific indices
arr2 = np.delete(arr1, [2,5])
print("After delete:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

After delete:
arr1 =  [93  3 28  5 97  8 51 32 15 83]
arr2 =  [93  3  5 97 51 32 15 83]


### b. Deleting Elements from a 2-D Arrays

**Example:** Delete a specific element from a 2-D array, don't mention the axis. The resulting array is flattened before use

In [28]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[6 3 4]
 [6 6 7]
 [2 4 3]]


In [29]:
arr2 = np.delete(arr1, 5)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After delete:
arr1 = 
 [[6 3 4]
 [6 6 7]
 [2 4 3]]
arr2 =  [6 3 4 6 6 2 4 3]


**Example:**  Delete a specific row from an existing 2-D array

In [30]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,4))
print("arr1 = \n", arr1)

arr1 = 
 [[4 2 3 4]
 [4 5 2 9]
 [9 7 2 6]
 [6 3 1 7]]


In [31]:
arr2 = np.delete(arr1, 2, axis=0)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After delete:
arr1 = 
 [[4 2 3 4]
 [4 5 2 9]
 [9 7 2 6]
 [6 3 1 7]]
arr2 = 
 [[4 2 3 4]
 [4 5 2 9]
 [6 3 1 7]]


**Example:**  Delete a specific column from an existing 2-D array

In [32]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,4))
print("arr1 = \n", arr1)

arr1 = 
 [[6 9 8 4]
 [7 3 1 5]
 [4 7 7 6]
 [9 3 8 2]]


In [33]:
arr2 = np.delete(arr1, 2, axis=1)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After delete:
arr1 = 
 [[6 9 8 4]
 [7 3 1 5]
 [4 7 7 6]
 [9 3 8 2]]
arr2 = 
 [[6 9 4]
 [7 3 5]
 [4 7 6]
 [9 3 2]]


## 5. Assigning vs Coping NumPy Arrays

### a. Assigning two NumPy Arrays (Create an alias)

In [34]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Creating a copy using assignment operator, both variables point at the same array
arr2 = arr1

print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [6 3 3 8 7 4 2 8 6 7]
arr2 =  [6 3 3 8 7 4 2 8 6 7]
1875357014736
1875357014736


In [35]:
# Change value in arr1 will also occur in arr2
arr2[2] = 55
print("arr1 = ", arr1)
print("arr2 = ", arr2)


arr1 =  [ 6  3 55  8  7  4  2  8  6  7]
arr2 =  [ 6  3 55  8  7  4  2  8  6  7]


### b. View/Shallow Copy
Arrays that share some data. The view method creates an object looking at the same data. Slicing an array returns a view of that array.

In [36]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Creating a shallow copy (view) using slice operator
arr2 = arr1[:]

print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [4 9 9 7 1 7 9 4 3 1]
arr2 =  [4 9 9 7 1 7 9 4 3 1]
1875357018288
1874984593392


In [37]:
# Change value in arr1 will occur in arr2
arr2[2] = 55

print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [ 4  9 55  7  1  7  9  4  3  1]
arr2 =  [ 4  9 55  7  1  7  9  4  3  1]


### c. Deep Copy

In [38]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Create a Deep copy using copy() method, which will create a new copy of the array
arr2 = arr1.copy()
print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [4 1 4 3 8 3 4 5 7 7]
arr2 =  [4 1 4 3 8 3 4 5 7 7]
1875357018480
1875357017616


In [39]:
# Change value in array 1 will NOT occur in array 2
arr2[2] = 55

print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [4 1 4 3 8 3 4 5 7 7]
arr2 =  [ 4  1 55  3  8  3  4  5  7  7]
