# Scenerio Based Practice

## Scenerio 1:
Create a 2D array representing sales data for 7 days across 3 stores. Use array creation functions to initialize the data. 
###### Compute:
 1- Total sales per store. <br>
 2- Day with maximum total sales. <br>
 3- Average sales across all stores.<br>

In [3]:
import numpy as np
sales_data = np.random.randint(100, 500, size=(7, 3))
print("Sales Data:\n", sales_data)
total_sales_per_store = np.sum(sales_data, axis=0)
print("Total Sales per Store:", total_sales_per_store)
total_sales_per_day = np.sum(sales_data, axis=1)
day_with_max_sales = max(total_sales_per_day)
print("Day with Maximum Total Sales:", day_with_max_sales)
average_sales = np.mean(sales_data)
print("Average Sales across All Stores:", average_sales)

Sales Data:
 [[411 210 312]
 [372 151 451]
 [449 292 197]
 [234 227 318]
 [296 296 497]
 [298 194 218]
 [121 177 320]]
Total Sales per Store: [2181 1547 2313]
Day with Maximum Total Sales: 1089
Average Sales across All Stores: 287.6666666666667


In [10]:
all_sum = 0
for i in range(3):
    summ = 0
    for j in range(7):
        summ += sales_data[j][i]
    print("Total Sales for Store", i+1, ":", summ)
    all_sum += summ
print(f"Average Sales across All Stores: {(all_sum/21)}")

transpose = [[sales_data[j][i] for j in range(7)] for i in range(3)]
col_sums = [sum(col) for col in transpose]
print("Maximum Sales in a Day:", col_sums.index(max(col_sums)))
    

Total Sales for Store 1 : 2181
Total Sales for Store 2 : 1547
Total Sales for Store 3 : 2313
Average Sales across All Stores: 287.6666666666667
Maximum Sales in a Day: 2


## Scenerio 2:
Scenario 2: Temperature Recording
Generate a NumPy array to simulate hourly temperature readings (24 hours) for a week.
###### Compute:

1- Identify the hour with the highest temperature each day. <br>
2- Calculate the daily average temperature.


In [13]:
import numpy as np
array = np.random.uniform(low=10, high= 45, size=(7,24))
print("Temperature Data:\n", array)
hourly_max = np.max(array, axis=1)
print("Hourly Max Temp:", hourly_max)
hourly_max_index = np.argmax(array, axis=1)
print("Hourly Max Temp Index:", hourly_max_index)
daily_avg = np.mean(array, axis=1)
print("Daily Average Temp:", daily_avg)


Temperature Data:
 [[25.64047557 19.55828055 33.92941859 37.16737068 29.02746005 14.32965033
  34.10949318 38.25511771 30.82749869 42.85463147 34.91584987 11.57552388
  34.05141225 42.94709485 18.3167464  23.35772185 23.13300296 19.30471594
  33.37503853 18.12923228 40.91292996 23.76065183 22.91187269 35.35691698]
 [33.00748762 31.93707195 43.99329571 18.2540545  19.98306721 31.99376211
  19.18260036 21.80823334 40.54229869 40.25533593 32.64926882 23.29875322
  33.81157019 35.44905529 25.66213855 19.17487641 35.97858745 34.40635827
  37.00415795 24.31475359 44.29258571 16.5426449  43.94020019 17.93747315]
 [35.90178508 34.21237875 27.06069553 16.35925806 24.73634599 34.38351372
  19.99485401 43.18906724 31.48295513 25.55945715 20.61704362 26.67399216
  19.2159232  17.99357813 20.90559206 12.15121435 13.67119318 20.35708037
  23.88557491 31.72115198 12.87962728 31.29015321 37.72373513 15.93941206]
 [39.0347204  16.33580285 25.18007973 14.87732598 26.52449664 35.58516378
  34.71658842 34